### ISSUE TITLE
406 Not Acceptable Error when sending login

### ISSUE THREAD

**Issue by mthompson2** [gcmvanloon/FoxEssCloudPoller#4]
I get the following error whenever i try to get a login token:

StatusCode: 406, ReasonPhrase: 'Not Acceptable', Version: 1.1

Any ideas?

Thanks

**Comment by gcmvanloon** [comment]
This error was caused by a change on the FoxEss Cloud side of things.
They have provided a new API that can be used by thirth party apps. I've updated the source code and the pre-build container to use this new API. This means you'll have to get an API key from the FoxEssCloud website and change the appsettings accordingly. (the readme is updated for more information on the configuration changes)
